version: '3.8'
services:
  tbot:
    build: .
    container_name: telegram-docker-monitor
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - LOG_POLL_INTERVAL=${LOG_POLL_INTERVAL:-1}
      - STREAM_RATE_LIMIT=${STREAM_RATE_LIMIT:-2}
      - USE_MOCK_DOCKER=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    # optionally provide more limits (security)
    # network_mode: host  # usually not necessary
